config/routes.rb
Rails.application.routes.draw do
  resources :books
  root :to => redirect('/books')
  get '/books/same_author_books/:id', to: 'books#same_author_books', as: :same_author_books
end

app/models/book.rb
class Book < ActiveRecord::Base
    
  #attr_accessible :title, :author, :rating, :Categories, :publication_date
  
  def self.all_ratings
    #%w(1 2 3 4 5)
    [1,2,3,4,5]  
  end
    
  def self.same_author_books(id)
    author = Book.find(id).author
    self.where(author: author)
  end
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  def index
    sort = params[:sort] || session[:sort]
    case sort
    when 'title'
      ordering,@title_header = {:title => :asc}, 'bg-warning hilite'
    when 'publication_date'
      ordering,@date_header = {:publication_date => :asc}, 'bg-warning hilite'
    end
    @all_ratings = Book.all_ratings
    @selected_ratings = params[:ratings] || session[:ratings] || {}

    if @selected_ratings == {}
      @selected_ratings = Hash[@all_ratings.map {|rating| [rating, rating]}]
    end

    if params[:sort] != session[:sort] or params[:ratings] != session[:ratings]
      session[:sort] = sort
      session[:ratings] = @selected_ratings
      redirect_to :sort => sort, :ratings => @selected_ratings and return
    end
    @books = Book.where(rating: @selected_ratings.keys).order(ordering)
      
    #Book.index(params[:index])
  end

  # GET /books/1
  def show
    id = params[:id] # retrieve book ID from URI route
    @book = Book.find(id) # look up book by unique ID
  end

  # GET /books/new
  def new
   @book = Book.new
  end

  # GET /books/1/edit
  def edit
      #@book = Book.find params[:id]
  end

  # POST /books
  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to @book, notice: 'Book was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /books/1
  def update
    if @book.update(book_params)
      redirect_to @book, notice: 'Book was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /books/1
  def destroy
    @book.destroy
    redirect_to books_url, notice: 'Book was successfully destroyed.'
  end
    
  def same_author_books
    @book = Book.find(params[:id])
      
    if @book.author.nil? || @book.author.empty?
        flash[:notice] = "'#{@book.title}' has no author info"
        redirect_to books_path
    else
        @books = Book.same_author_books(params[:id])
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def book_params
      params.require(:book).permit(:title, :author, :rating, :Categories, :description, :publication_date)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= stylesheet_link_tag "application", :media => "all" %>
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.text_field :rating %>
  </div>
  <div class="field">
    <%= f.label :Categories %><br>
    <%= f.text_field :Categories %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :publication_date %><br>
    <%= f.text_field :publication_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<%= stylesheet_link_tag "application", :media => "all" %>
<h1>Edit Editing Book</h1>

<%= render 'form' %>
<br/>
<%= link_to 'Show', @book , :class => 'btn btn-primary col-2' %> |
<%= link_to 'Back to book list', books_path , :class => 'btn btn-primary col-2' %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>
<%= stylesheet_link_tag "application", :media => "all" %>

<h1>READING CHALLENGE</h1>

<h2>All Books</h2>

<%= form_tag books_path, method: :get, id: 'ratings_form' do %>
  <%= hidden_field_tag "title_sort", true if @title_header %>
  <%= hidden_field_tag ":publication_date_sort", true if @date_header %>
  Include :
  <% @all_ratings.each do |rating| %>
    <div class="form-check  form-check-inline">
      <%= rating %>
      <%= check_box_tag "ratings[#{rating}]", "1",  @selected_ratings.include?(rating),  :id => "ratings_#{rating}" %>
    </div>
  <% end %>
  <%= submit_tag 'Refresh', id: 'ratings_submit', class: 'btn btn-primary col-2' %>
<% end %>

<table class="styled-table center" id="books">
  <thead>
    <tr>
      <th>
        <%= link_to 'Book Title', books_path(:sort => 'title', :ratings => @selected_ratings), :id => 'title_header',:class => @title_header %>
      </th>
      <th>Author</th>
      <th>Rating</th>
      <th>Categories</th>
      <th>Description</th>
      <th>
        <%= link_to 'Publication Date', books_path(:sort => 'publication_date', :ratings => @selected_ratings), :id => 'publication_date_header',:class => @date_header %>
      </th>
      <th>More Info</th>
      <th>Find Books With Same Author</th>
      <th>Edit</th>
      <th>Delete</th>
      <th colspan="6"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.rating %></td>
        <td><%= book.Categories %></td>
        <td><%= book.description %></td>
        <td><%= book.publication_date %></td>
        <td>
          <%= link_to "More about #{book.title}", book_path(book) %>
        </td>
        <td>
           <%= link_to "Find Books With Same Author #{book.author}", same_author_books_path(book) %>
        </td>
        <td><%= link_to 'Edit', edit_book_path(book),:class => 'btn btn-success' %></td>
        <td><%= link_to 'Delete', book, method: :delete,:class => 'btn btn-danger',data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path , :class => 'btn btn-primary col-2'%>

app/views/books/new.html.erb
<%= stylesheet_link_tag "application", :media => "all" %>
<h1>Create New Book</h1>

<%= render 'form' %>

<%= link_to 'Back to book list', books_path, :class => 'btn btn-primary col-2' %>

app/views/books/same_author.html.erb
<p id="notice"><%= notice %></p>
<%= stylesheet_link_tag "application", :media => "all" %>

<h2>Books</h2>

<table class="styled-table center" id="books">
  <thead>
    <tr>
      <th>Book Title</th>
      <th>Author</th>
      <th>Rating</th>
      <th>Categories</th>
      <th>Description</th>
      <th>Publication Date</th>
      <th>More Info</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Destroy</th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.rating %></td>
        <td><%= book.Categories %></td>
        <td><%= book.description %></td>
        <td><%= book.publication_date %></td>
        <td>
          <%= link_to "More about #{book.title}", book_path(book) %>
        </td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path , :class => 'btn btn-primary col-2'%>

app/views/books/same_author_books.html.erb
<p id="notice"><%= notice %></p>
<%= stylesheet_link_tag "application", :media => "all" %>

<h2>Books</h2>

<table class="styled-table center" id="books">
  <thead>
    <tr>
      <th>Book Title</th>
      <th>Author</th>
      <th>Rating</th>
      <th>Categories</th>
      <th>Description</th>
      <th>Publication Date</th>
      <th>More Info</th>
      <th>Edit</th>
      <th>Destroy</th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.rating %></td>
        <td><%= book.Categories %></td>
        <td><%= book.description %></td>
        <td><%= book.publication_date %></td>
        <td>
          <%= link_to "More about #{book.title}", book_path(book) %>
        </td>
        <td><%= link_to 'Edit', edit_book_path(book),:class => 'btn btn-success' %></td>
        <td><%= link_to 'Destroy', book, method: :delete,:class => 'btn btn-danger', data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path , :class => 'btn btn-primary col-2'%>
<%= link_to 'Back to book list', books_path , :class => 'btn btn-primary col-2' %>

app/views/books/show.html.erb
<%= stylesheet_link_tag "application", :media => "all" %>
<p id="notice"><%= notice %></p>

<h2>Details about <em><%= @book.title %></em></h2>
<br>
<ul id="details">
    
<li>
  <strong>Title:</strong>
  <%= @book.title %>
</li>

<li>
  <strong>Author:</strong>
  <%= @book.author %>
</li>

<li>
  <strong>Rating:</strong>
  <%= @book.rating %>
</li>

<li>
  <strong>Categories:</strong>
  <%= @book.Categories %>
</li>


<li>
  <strong>Publication Date:</strong>
  <%= @book.publication_date %>
</li>
   
</ul>

<h3>Description:</h3>
<p id="description">
  <%= @book.description %>
</p>

<%= link_to 'Edit', edit_book_path(@book) , :class => 'btn btn-primary col-2' %> |
<%= link_to 'Delete', book_path(@book), 'data-method' => 'delete', 'data-confirm' => 'Are you sure?', :class => 'btn btn-danger col-2' %>
<%= link_to 'Back to book list', books_path , :class => 'btn btn-primary col-2'%>
<%= link_to 'Find Books With Same Author',  same_author_books_path(@book), :class => 'btn btn-primary' %>

app/views/layouts/_flash.erb
<% if flash[:notice] %>
  <div class="alert alert-info" role="alert" id="notice">
    <%= flash[:notice] %>
  </div>
<% elsif flash[:warning] %>
  <div class="alert alert-danger" role="alert" id="warning">
    <%= flash[:warning] %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<%# Our "base" layout should be a valid HTML document. %>
<!DOCTYPE html>
<html>
  <head>
    <title>JinaKim_G00353420</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', 'media' => 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%# These classes come from the Bootstrap CSS framework. %>
    <nav class="navbar navbar-expand-lg primary text-white mb-3">
      <h1 class="title">Final Project</h1>
    </nav>
    <div class="container">
      <%# Render "flash" messages in our application. This loads _flash.erb %>
      <%= render 'layouts/flash' %>
      <main id="main">
        <%= yield %>
      </main>
    </div>
  </body>
</html>